name: Bug Report
description: File a bug report
labels: ["bug"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Although the primary language of this project is english, please feel free to use german, if you prefer.
  - type: input
    id: username_or_email
    attributes:
      label: Bootstrap Academy username
      description: Please enter your username or email address of your Bootstrap Academy account!
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. user@gmail.com / @user:matrix.org
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - "Other (please specify below)"
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please describe the problem as precisely as possible. What are you trying to do? What did you expect to happen and what happened instead? If applicable, you can also include screenshots / screen recordings to help illustrate the problem. The more information, the better!
      placeholder: "A bug happened!"
    validations:
      required: true
