blank_issues_enabled: true
contact_links:
  - name: Discord
    url: "https://the-morpheus.de/discord.html"
    about: "Join the Discord server of The Morpheus Tutorials."
  - name: Bootstrap Academy
    url: "https://bootstrap.academy/contact"
    about: "Go to https://bootstrap.academy/contact for information on how to contact us."
