name: Feature Request
description: Suggest an improvement to Bootstrap Academy
labels: ["enhancement"]
projects: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! English and German are both welcome.

        This suggestion is public. Leave out personal details and hide private information in screenshots.
        We use your feedback to improve the platform. For a personal reply, contact us by [email](https://bootstrap.academy/docs/imprint).
  - type: textarea
    id: description
    attributes:
      label: What would you like to improve?
      description: How would your idea help you learn?
    validations:
      required: true
